### PR TITLE
Refactored Supermarket program to use  functions

### PR DESCRIPTION
**Pull request by dom-edu**
refactored supermarket program to use functions and new lines

### CODE REVIEW

**Comment by dom-edu** [comment]
Take a look at my refactor using functions, that should give you some ideas !

**Comment by Rushbrush250** [comment]
Sorry it took a while to reach out, I going to start adding your pulls separately instead of merging, thx a lot for your help.

**Comment by Rushbrush250** [comment]
Also yes it gave me lots of ideas.

**Comment by Rushbrush250** [comment]
From now on when taking some project or pull not made by me I’m putting “Alt” in front.

**Comment by Rushbrush250** [comment]
Thanks a lot

**Pull request closed without merging**
